### PR TITLE
fix: useDeepCompareEffect

### PR DESCRIPTION
**Pull request by ufkaya**
We have tried a couple of solutions and this is the one that works

Note: I will check in which case the user can be null/undefined

### CODE REVIEW

**Review by lkappeler — COMMENTED** [review]
Can you please add some more context on the Issue and the suggested solution? It's very hard to review without any context.

**Comment by ufkaya** [comment]
> Can you please add some more context on the Issue and the suggested solution? It's very hard to review without any context.

In the dependencies of useDeepCompareEffect we have the object user which sometimes is a primitive, and we get an error because if we only have primitive data as dependencies we should use useEffect instead.

By assigning a default value to the user I make sure it is always an object, and I didnt find why the user can be primitive...

**Comment by ufkaya** [comment]
after another test, this does not solve the bug 😞

**Comment by masone** [comment]
the context you gave with https://github.com/carforyou/carforyou-ld-pkg/pull/91#issuecomment-919129924 was very helpful. keep it up! 👍

**Comment by ufkaya** [comment]
update: the error occurs when ldData is null which happens if we dont use propagatePageProps or handleServerSidePropsError (which includes the same fn), therefore, is better to fix it in the listings project and not here

**Pull request closed without merging**
